import type { SentenceProps } from "@/components/features/sentence";

export const motivationalSentences: (SentenceProps & { id: number })[] = [
	{
		id: 1,
		text: "A única maneira de fazer um excelente trabalho é amar o que você faz.",
		author: "Steve Jobs",
		year: "2005",
	},
	{
		id: 2,
		text: "A mente que se abre a uma nova ideia jamais voltará ao seu tamanho original.",
		author: "Albert Einstein",
		year: "1931",
	},
	{
		id: 3,
		text: "Se você pode sonhar, você pode realizar.",
		author: "Walt Disney",
		year: "1955",
	},
	{
		id: 4,
		text: "Não importa o quão devagar você vá, desde que não pare.",
		author: "Confúcio",
		year: "500 a.C.",
	},
	{
		id: 5,
		text: "Tudo parece impossível até que seja feito.",
		author: "Nelson Mandela",
		year: "1994",
	},
	{
		id: 6,
		text: "O futuro pertence àqueles que acreditam na beleza de seus sonhos.",
		author: "Eleanor Roosevelt",
		year: "1937",
	},
	{
		id: 7,
		text: "O sucesso é ir de fracasso em fracasso sem perder o entusiasmo.",
		author: "Winston Churchill",
		year: "1941",
	},
	{
		id: 8,
		text: "Seja a mudança que você quer ver no mundo.",
		author: "Mahatma Gandhi",
		year: "1913",
	},
	{
		id: 9,
		text: "Acredite que você pode e você já está no meio do caminho.",
		author: "Theodore Roosevelt",
		year: "1910",
	},
	{
		id: 10,
		text: "Se você quer ser bem-sucedido, precisa ter dedicação total e buscar seu último limite.",
		author: "Ayrton Senna",
		year: "1991",
	},
	{
		id: 11,
		text: "Renda-se ao que é, desapegue do que foi, tenha fé no que será.",
		author: "Clarice Lispector",
		year: "1977",
	},
	{
		id: 12,
		text: "Tudo vale a pena se a alma não é pequena.",
		author: "Fernando Pessoa",
		year: "1934",
	},
	{
		id: 13,
		text: "Quando você quer uma coisa, todo o universo conspira para que você a realize.",
		author: "Paulo Coelho",
		year: "1988",
	},
	{
		id: 14,
		text: "Você pode não controlar todos os eventos, mas pode decidir não ser reduzido por eles.",
		author: "Maya Angelou",
		year: "1978",
	},
	{
		id: 15,
		text: "Os dois dias mais importantes da sua vida são o dia em que você nasce e o dia em que descobre o porquê.",
		author: "Mark Twain",
		year: "1884",
	},
	{
		id: 16,
		text: "Se não puder voar, corra. Se não puder correr, ande. Se não puder andar, rasteje, mas continue em frente.",
		author: "Martin Luther King Jr.",
		year: "1963",
	},
	{
		id: 17,
		text: "A única coisa pior do que não ter visão é ter visão, mas não ter coragem de agir.",
		author: "Helen Keller",
		year: "1903",
	},
	{
		id: 18,
		text: "Nós somos o que fazemos repetidamente. A excelência, portanto, não é um ato, mas um hábito.",
		author: "Aristóteles",
		year: "350 a.C.",
	},
	{
		id: 19,
		text: "Uma vida sem busca e reflexão não vale a pena ser vivida.",
		author: "Sócrates",
		year: "400 a.C.",
	},
	{
		id: 20,
		text: "Não é porque as coisas são difíceis que não ousamos; é porque não ousamos que elas são difíceis.",
		author: "Sêneca",
		year: "65",
	},
	{
		id: 21,
		text: "Aquele que tem um porquê para viver pode suportar quase qualquer como.",
		author: "Friedrich Nietzsche",
		year: "1889",
	},
	{
		id: 22,
		text: "Uma jornada de mil milhas começa com um único passo.",
		author: "Lao Tzu",
		year: "600 a.C.",
	},
	{
		id: 23,
		text: "A maior vitória é aquela que não requer batalha.",
		author: "Sun Tzu",
		year: "500 a.C.",
	},
	{
		id: 24,
		text: "Seja você mesmo; todos os outros papéis já estão ocupados.",
		author: "Oscar Wilde",
		year: "1890",
	},
	{
		id: 25,
		text: "Quer você pense que pode ou pense que não pode, você está certo.",
		author: "Henry Ford",
		year: "1922",
	},
	{
		id: 26,
		text: "Nossa maior fraqueza está em desistir. O caminho mais certo para ter sucesso é tentar mais uma vez.",
		author: "Thomas Edison",
		year: "1879",
	},
	{
		id: 27,
		text: "Não é o mais forte que sobrevive, mas o que melhor se adapta às mudanças.",
		author: "Charles Darwin",
		year: "1859",
	},
	{
		id: 28,
		text: "Nada na vida deve ser temido, apenas compreendido.",
		author: "Marie Curie",
		year: "1911",
	},
	{
		id: 29,
		text: "Lembre-se de olhar para as estrelas e não para os seus pés.",
		author: "Stephen Hawking",
		year: "1988",
	},
	{
		id: 30,
		text: "Como é maravilhoso que ninguém precisa esperar um único momento antes de começar a melhorar o mundo.",
		author: "Anne Frank",
		year: "1944",
	},
	{
		id: 31,
		text: "Escreva algo que valha a pena ler ou faça algo que valha a pena escrever.",
		author: "Benjamin Franklin",
		year: "1750",
	},
	{
		id: 32,
		text: "O que está atrás de nós e o que está à nossa frente são questões menores comparadas ao que está dentro de nós.",
		author: "Ralph Waldo Emerson",
		year: "1841",
	},
	{
		id: 33,
		text: "Mesmo a noite mais escura terminará e o sol nascerá.",
		author: "Victor Hugo",
		year: "1862",
	},
	{
		id: 34,
		text: "O fracasso é o tempero que dá sabor ao sucesso.",
		author: "Dale Carnegie",
		year: "1936",
	},
	{
		id: 35,
		text: "A melhor maneira de prever o futuro é criá-lo.",
		author: "Abraham Lincoln",
		year: "1863",
	},
	{
		id: 36,
		text: "A felicidade da sua vida depende da qualidade dos seus pensamentos.",
		author: "Marco Aurélio",
		year: "170",
	},
	{
		id: 37,
		text: "Se você não está disposto a arriscar o habitual, terá que se contentar com o comum.",
		author: "Jim Rohn",
		year: "1985",
	},
	{
		id: 38,
		text: "Você não precisa ser ótimo para começar, mas precisa começar para ser ótimo.",
		author: "Zig Ziglar",
		year: "1975",
	},
	{
		id: 39,
		text: "Mire na lua. Mesmo se você errar, estará entre as estrelas.",
		author: "Les Brown",
		year: "1992",
	},
	{
		id: 40,
		text: "Você se torna aquilo em que acredita.",
		author: "Oprah Winfrey",
		year: "2000",
	},
	{
		id: 41,
		text: "Não reze por uma vida fácil, reze por forças para suportar uma vida difícil.",
		author: "Bruce Lee",
		year: "1971",
	},
	{
		id: 42,
		text: "Eu errei mais de 9000 arremessos na minha carreira. Foi por isso que eu venci.",
		author: "Michael Jordan",
		year: "1997",
	},
	{
		id: 43,
		text: "Não conte os dias, faça os dias contarem.",
		author: "Muhammad Ali",
		year: "1974",
	},
	{
		id: 44,
		text: "Se você tem medo de falhar, provavelmente vai falhar.",
		author: "Kobe Bryant",
		year: "2008",
	},
	{
		id: 45,
		text: "O sucesso não é por acaso. É trabalho duro, perseverança e aprendizado.",
		author: "Pelé",
		year: "1970",
	},
	{
		id: 46,
		text: "Onde quer que você esteja na vida, sempre há espaço para crescer.",
		author: "Serena Williams",
		year: "2015",
	},
	{
		id: 47,
		text: "Seus sonhos são seus, não deixe ninguém tirar o valor deles.",
		author: "Cristiano Ronaldo",
		year: "2016",
	},
	{
		id: 48,
		text: "Treinei anos para correr segundos. Não desista por causa do tempo que vai levar.",
		author: "Usain Bolt",
		year: "2012",
	},
	{
		id: 49,
		text: "É impossível viver sem falhar em algo, a menos que você viva tão cautelosamente que não tenha vivido.",
		author: "J.K. Rowling",
		year: "2008",
	},
	{
		id: 50,
		text: "A vida não é sobre encontrar a si mesmo. A vida é sobre criar a si mesmo.",
		author: "George Bernard Shaw",
		year: "1903",
	},
	{
		id: 51,
		text: "O essencial é invisível aos olhos.",
		author: "Antoine de Saint-Exupéry",
		year: "1943",
	},
	{
		id: 52,
		text: "Não chore porque acabou, sorria porque aconteceu.",
		author: "Gabriel García Márquez",
		year: "1981",
	},
	{
		id: 53,
		text: "O real não está no saída nem na chegada: ele se dispõe para a gente é no meio da travessia.",
		author: "Guimarães Rosa",
		year: "1956",
	},
	{
		id: 54,
		text: "No meio do caminho tinha uma pedra, mas eu aprendi a caminhar.",
		author: "Carlos Drummond de Andrade",
		year: "1945",
	},
	{
		id: 55,
		text: "O que vale na vida não é o ponto de partida e sim a caminhada.",
		author: "Cora Coralina",
		year: "1983",
	},
	{
		id: 56,
		text: "Eles passarão... eu passarinho!",
		author: "Mario Quintana",
		year: "1980",
	},
	{
		id: 57,
		text: "Recria tua vida, sempre, em todo livre movimento. Desfaze o ninho e voa.",
		author: "Cecília Meireles",
		year: "1950",
	},
	{
		id: 58,
		text: "Não tive filhos, não transmiti a nenhuma criatura o legado da nossa miséria, mas deixo a esperança.",
		author: "Machado de Assis",
		year: "1881",
	},
	{
		id: 59,
		text: "Conhecimento é poder.",
		author: "Francis Bacon",
		year: "1620",
	},
	{
		id: 60,
		text: "Penso, logo existo. Crio, logo realizo.",
		author: "René Descartes",
		year: "1637",
	},
	{
		id: 61,
		text: "Tenha a coragem de usar seu próprio entendimento.",
		author: "Immanuel Kant",
		year: "1784",
	},
	{
		id: 62,
		text: "A dúvida é o princípio da sabedoria.",
		author: "Voltaire",
		year: "1759",
	},
	{
		id: 63,
		text: "O homem nasceu livre, e por toda parte ele deve lutar para manter sua liberdade.",
		author: "Jean-Jacques Rousseau",
		year: "1762",
	},
	{
		id: 64,
		text: "Tudo o que é excelente é tão difícil quanto raro.",
		author: "Baruch Spinoza",
		year: "1677",
	},
	{
		id: 65,
		text: "A ação é o combustível que transforma desejos em realidade.",
		author: "Arthur Schopenhauer",
		year: "1851",
	},
	{
		id: 66,
		text: "Onde a vontade é grande, as dificuldades não podem ser grandes.",
		author: "Maquiavel",
		year: "1532",
	},
	{
		id: 67,
		text: "Todas as verdades são fáceis de entender depois de descobertas; o ponto é descobri-las.",
		author: "Galileu Galilei",
		year: "1632",
	},
	{
		id: 68,
		text: "Se vi mais longe, foi por estar sobre os ombros de gigantes.",
		author: "Isaac Newton",
		year: "1687",
	},
	{
		id: 69,
		text: "Se você quiser descobrir os segredos do universo, pense em termos de energia, frequência e vibração.",
		author: "Nikola Tesla",
		year: "1919",
	},
	{
		id: 70,
		text: "O primeiro princípio é que você não deve se enganar a si mesmo.",
		author: "Richard Feynman",
		year: "1965",
	},
	{
		id: 71,
		text: "Em algum lugar, algo incrível está esperando para ser conhecido.",
		author: "Carl Sagan",
		year: "1980",
	},
	{
		id: 72,
		text: "A boa coisa sobre a ciência é que ela é verdadeira, quer você acredite nela ou não.",
		author: "Neil deGrasse Tyson",
		year: "2014",
	},
	{
		id: 73,
		text: "A simplicidade é o ápice da sofisticação.",
		author: "Leonardo da Vinci",
		year: "1500",
	},
	{
		id: 74,
		text: "O maior perigo para a maioria de nós não é que nosso alvo seja alto demais e o erremos, mas que seja baixo demais e o alcancemos.",
		author: "Michelangelo",
		year: "1530",
	},
	{
		id: 75,
		text: "Se você ouvir uma voz dentro de você dizendo 'você não pode pintar', pinte e essa voz será silenciada.",
		author: "Vincent van Gogh",
		year: "1882",
	},
	{
		id: 76,
		text: "A ação é a chave fundamental para todo o sucesso.",
		author: "Pablo Picasso",
		year: "1932",
	},
	{
		id: 77,
		text: "Pés, para que os quero, se tenho asas para voar?",
		author: "Frida Kahlo",
		year: "1953",
	},
	{
		id: 78,
		text: "Não tenha medo da perfeição - você nunca a alcançará.",
		author: "Salvador Dalí",
		year: "1968",
	},
	{
		id: 79,
		text: "Eles sempre dizem que o tempo muda as coisas, mas você é quem tem que mudá-las.",
		author: "Andy Warhol",
		year: "1975",
	},
	{
		id: 80,
		text: "A coragem começa com nos mostrarmos e nos deixarmos ser vistos.",
		author: "Brené Brown",
		year: "2012",
	},
	{
		id: 81,
		text: "As pessoas não compram o que você faz; elas compram o porquê de você fazer.",
		author: "Simon Sinek",
		year: "2009",
	},
	{
		id: 82,
		text: "Você não sobe ao nível das suas metas, você cai ao nível dos seus sistemas.",
		author: "James Clear",
		year: "2018",
	},
	{
		id: 83,
		text: "Mudar de atitude mental transforma a maneira como enfrentamos os desafios.",
		author: "Carol Dweck",
		year: "2006",
	},
	{
		id: 84,
		text: "Garra é a combinação de paixão e perseverança para objetivos de longo prazo.",
		author: "Angela Duckworth",
		year: "2016",
	},
	{
		id: 85,
		text: "Um livro, uma caneta, uma criança e um professor podem mudar o mundo.",
		author: "Malala Yousafzai",
		year: "2013",
	},
	{
		id: 86,
		text: "Sua história é o que você tem, o que você sempre terá. É algo para se orgulhar.",
		author: "Michelle Obama",
		year: "2018",
	},
	{
		id: 87,
		text: "A mudança não virá se esperarmos por outra pessoa ou outro momento. Nós somos aqueles por quem esperávamos.",
		author: "Barack Obama",
		year: "2008",
	},
	{
		id: 88,
		text: "Você pode ser o primeiro a fazer muitas coisas, mas garanta que não será o último.",
		author: "Kamala Harris",
		year: "2020",
	},
	{
		id: 89,
		text: "O trabalho ocupa uma grande parte da sua vida, faça algo em que você realmente acredite.",
		author: "Tim Cook",
		year: "2017",
	},
	{
		id: 90,
		text: "Sua marca é o que as pessoas dizem sobre você quando você não está na sala.",
		author: "Jeff Bezos",
		year: "2010",
	},
	{
		id: 91,
		text: "Comemorar o sucesso é ótimo, mas é mais importante prestar atenção às lições do fracasso.",
		author: "Bill Gates",
		year: "1996",
	},
	{
		id: 92,
		text: "O maior risco é não arriscar nada num mundo que muda rapidamente.",
		author: "Mark Zuckerberg",
		year: "2012",
	},
	{
		id: 93,
		text: "Se algo é importante o suficiente, você deve tentar, mesmo que o resultado provável seja o fracasso.",
		author: "Elon Musk",
		year: "2014",
	},
	{
		id: 94,
		text: "Nossa indústria não respeita a tradição - ela só respeita a inovação.",
		author: "Satya Nadella",
		year: "2017",
	},
	{
		id: 95,
		text: "Arme-se de conhecimento e construa seus próprios julgamentos.",
		author: "Naval Ravikant",
		year: "2019",
	},
	{
		id: 96,
		text: "Você tem poder sobre sua mente, não sobre eventos externos. Perceba isso e encontrará sua força.",
		author: "Marco Aurélio",
		year: "175",
	},
	{
		id: 97,
		text: "Não são as coisas que nos perturbam, mas a visão que temos delas.",
		author: "Epicteto",
		year: "100",
	},
	{
		id: 98,
		text: "A sorte é o que acontece quando a preparação encontra a oportunidade.",
		author: "Sêneca",
		year: "62",
	},
	{
		id: 99,
		text: "No meio do caos, também há oportunidade.",
		author: "Sun Tzu",
		year: "505 a.C.",
	},
	{
		id: 100,
		text: "A única constante na vida é a mudança.",
		author: "Heráclito",
		year: "500 a.C.",
	},
	{
		id: 101,
		text: "Nada vem do nada; construa suas fundações.",
		author: "Parmênides",
		year: "475 a.C.",
	},
	{
		id: 102,
		text: "Esculpa sua própria estátua até que ela brilhe com virtude.",
		author: "Plotino",
		year: "260",
	},
	{
		id: 103,
		text: "Enquanto há vida, há esperança.",
		author: "Cícero",
		year: "44 a.C.",
	},
	{
		id: 104,
		text: "A persistência é o caminho do êxito.",
		author: "Charles Chaplin",
		year: "1940",
	},
	{
		id: 105,
		text: "Não tente ser uma pessoa de sucesso, mas sim uma pessoa de valor.",
		author: "Albert Einstein",
		year: "1955",
	},
	{
		id: 106,
		text: "A melhor vingança é não ser como o seu inimigo.",
		author: "Marco Aurélio",
		year: "170",
	},
	{
		id: 107,
		text: "Não podemos escolher nossas circunstâncias externas, mas podemos escolher como responder a elas.",
		author: "Epicteto",
		year: "105",
	},
	{
		id: 108,
		text: "É durante a tempestade que conhecemos o bom piloto.",
		author: "Sêneca",
		year: "60",
	},
	{
		id: 109,
		text: "Quando não podemos mais mudar uma situação, somos desafiados a mudar a nós mesmos.",
		author: "Viktor Frankl",
		year: "1946",
	},
	{
		id: 110,
		text: "Você nunca é velho demais para definir outro objetivo ou sonhar um novo sonho.",
		author: "C.S. Lewis",
		year: "1952",
	},
	{
		id: 111,
		text: "Faça o que puder, com o que tiver, onde estiver.",
		author: "Theodore Roosevelt",
		year: "1901",
	},
	{
		id: 112,
		text: "Sozinhos podemos fazer tão pouco; juntos podemos fazer muito.",
		author: "Helen Keller",
		year: "1925",
	},
	{
		id: 113,
		text: "Mantenha-se faminto, mantenha-se tolo.",
		author: "Steve Jobs",
		year: "2005",
	},
	{
		id: 114,
		text: "Se você não gosta de algo, mude. Se não puder mudar, mude sua atitude.",
		author: "Maya Angelou",
		year: "1993",
	},
	{
		id: 115,
		text: "Duas estradas divergiam em um bosque, e eu peguei a menos percorrida.",
		author: "Robert Frost",
		year: "1916",
	},
	{
		id: 116,
		text: "A única pessoa que você está destinado a se tornar é a pessoa que você decide ser.",
		author: "Ralph Waldo Emerson",
		year: "1870",
	},
	{
		id: 117,
		text: "A nossa maior glória não reside em jamais cair, mas em levantarmo-nos sempre que caímos.",
		author: "Confúcio",
		year: "500 a.C.",
	},
	{
		id: 118,
		text: "Tu te tornas eternamente responsável por aquilo que cativas.",
		author: "Antoine de Saint-Exupéry",
		year: "1943",
	},
	{
		id: 119,
		text: "Aquele que conhece os outros é sábio; aquele que conhece a si mesmo é iluminado.",
		author: "Lao Tzu",
		year: "600 a.C.",
	},
	{
		id: 120,
		text: "A maneira de começar é parar de falar e começar a fazer.",
		author: "Walt Disney",
		year: "1948",
	},
	{
		id: 121,
		text: "A coragem é a primeira das virtudes humanas porque garante todas as outras.",
		author: "Winston Churchill",
		year: "1930",
	},
	{
		id: 122,
		text: "A educação é a arma mais poderosa que você pode usar para mudar o mundo.",
		author: "Nelson Mandela",
		year: "2003",
	},
	{
		id: 123,
		text: "A imaginação é mais importante que o conhecimento.",
		author: "Albert Einstein",
		year: "1929",
	},
	{
		id: 124,
		text: "A escuridão não pode expulsar a escuridão; apenas a luz pode fazer isso.",
		author: "Martin Luther King Jr.",
		year: "1963",
	},
	{
		id: 125,
		text: "No final, não são os anos da sua vida que contam. É a vida nos seus anos.",
		author: "Abraham Lincoln",
		year: "1860",
	},
	{
		id: 126,
		text: "Coragem é a resistência ao medo, o domínio do medo - não a ausência dele.",
		author: "Mark Twain",
		year: "1894",
	},
	{
		id: 127,
		text: "Viver é a coisa mais rara do mundo. A maioria das pessoas apenas existe.",
		author: "Oscar Wilde",
		year: "1891",
	},
	{
		id: 128,
		text: "Sem música, a vida seria um erro.",
		author: "Friedrich Nietzsche",
		year: "1889",
	},
	{
		id: 129,
		text: "A suprema arte da guerra é derrotar o inimigo sem lutar.",
		author: "Sun Tzu",
		year: "500 a.C.",
	},
	{
		id: 130,
		text: "As pessoas que vencem neste mundo são as que procuram as circunstâncias de que precisam.",
		author: "George Bernard Shaw",
		year: "1893",
	},
	{
		id: 131,
		text: "Diga-me e eu esqueço. Ensine-me e eu lembro. Envolva-me e eu aprendo.",
		author: "Benjamin Franklin",
		year: "1750",
	},
	{
		id: 132,
		text: "Vá confiante na direção dos seus sonhos. Viva a vida que você imaginou.",
		author: "Henry David Thoreau",
		year: "1854",
	},
	{
		id: 133,
		text: "Quando você elimina o impossível, o que sobra, por mais improvável que seja, deve ser a verdade.",
		author: "Arthur Conan Doyle",
		year: "1890",
	},
	{
		id: 134,
		text: "É preciso ter perseverança e, acima de tudo, confiança em nós mesmos.",
		author: "Marie Curie",
		year: "1903",
	},
	{
		id: 135,
		text: "Eu atribuo meu sucesso a isso: nunca dei ou aceitei uma desculpa.",
		author: "Florence Nightingale",
		year: "1861",
	},
	{
		id: 136,
		text: "O mais difícil é a decisão de agir, o resto é apenas tenacidade.",
		author: "Amelia Earhart",
		year: "1932",
	},
	{
		id: 137,
		text: "Cada pessoa deve viver sua vida como um modelo para os outros.",
		author: "Rosa Parks",
		year: "1992",
	},
	{
		id: 138,
		text: "Todo grande sonho começa com um sonhador.",
		author: "Harriet Tubman",
		year: "1896",
	},
	{
		id: 139,
		text: "Não há barreira, fechadura ou ferrolho que você possa impor à liberdade da minha mente.",
		author: "Virginia Woolf",
		year: "1929",
	},
	{
		id: 140,
		text: "Não há charme igual à ternura de coração.",
		author: "Jane Austen",
		year: "1815",
	},
	{
		id: 141,
		text: "A esperança é a coisa com penas que pousa na alma.",
		author: "Emily Dickinson",
		year: "1861",
	},
	{
		id: 142,
		text: "Aprendi que as pessoas vão esquecer o que você disse, mas nunca como você as fez sentir.",
		author: "Maya Angelou",
		year: "2003",
	},
	{
		id: 143,
		text: "Nem tudo o que é enfrentado pode ser modificado, mas nada pode ser modificado até que seja enfrentado.",
		author: "James Baldwin",
		year: "1962",
	},
	{
		id: 144,
		text: "Quando eu me atrevo a ser poderosa, minha coragem torna-se mais importante do que meu medo.",
		author: "Audre Lorde",
		year: "1984",
	},
	{
		id: 145,
		text: "Se há um livro que você quer ler, mas ainda não foi escrito, você deve escrevê-lo.",
		author: "Toni Morrison",
		year: "1981",
	},
	{
		id: 146,
		text: "A vida não é a que a gente viveu, mas a que a gente recorda para contá-la.",
		author: "Gabriel García Márquez",
		year: "2002",
	},
	{
		id: 147,
		text: "Sempre imaginei que o paraíso fosse uma espécie de biblioteca.",
		author: "Jorge Luis Borges",
		year: "1975",
	},
	{
		id: 148,
		text: "Não se renda, por favor não ceda, embora o frio queime, embora o medo morda.",
		author: "Mario Benedetti",
		year: "1984",
	},
	{
		id: 149,
		text: "Você é livre para fazer suas escolhas, mas é prisioneiro das consequências.",
		author: "Pablo Neruda",
		year: "1950",
	},
	{
		id: 150,
		text: "A sabedoria consiste em saber que se pode aprender com qualquer pessoa.",
		author: "Octavio Paz",
		year: "1980",
	},
	{
		id: 151,
		text: "A aceitação da dor é o primeiro passo para superá-la.",
		author: "Isabel Allende",
		year: "1994",
	},
	{
		id: 152,
		text: "Se a educação sozinha não transforma a sociedade, sem ela tampouco a sociedade muda.",
		author: "Paulo Freire",
		year: "1968",
	},
	{
		id: 153,
		text: "O otimista é um tolo; o pessimista, um chato; bom mesmo é ser um realista esperançoso.",
		author: "Ariano Suassuna",
		year: "2005",
	},
	{
		id: 154,
		text: "A crise da educação não é uma crise; é um projeto.",
		author: "Darcy Ribeiro",
		year: "1978",
	},
	{
		id: 155,
		text: "A minha vontade é forte, mas a minha coragem de demonstrá-la é maior.",
		author: "Carlos Drummond de Andrade",
		year: "1960",
	},
	{
		id: 156,
		text: "Há noites em que não posso dormir de tanta felicidade que sinto dentro de mim.",
		author: "Cecília Meireles",
		year: "1942",
	},
	{
		id: 157,
		text: "Sua vida não é um rascunho, passe a limpo hoje mesmo.",
		author: "Mário de Andrade",
		year: "1928",
	},
	{
		id: 158,
		text: "A beleza não está nas coisas, mas na luz que projetamos sobre elas.",
		author: "Lygia Fagundes Telles",
		year: "1973",
	},
	{
		id: 159,
		text: "Eles combinaram de nos matar, mas nós combinamos de não morrer.",
		author: "Conceição Evaristo",
		year: "2014",
	},
	{
		id: 160,
		text: "Lutar contra as injustiças é um compromisso diário com a nossa própria humanidade.",
		author: "Djamila Ribeiro",
		year: "2017",
	},
	{
		id: 161,
		text: "A verdadeira viagem não está em ver novas paisagens, mas em ter novos olhos.",
		author: "Mia Couto",
		year: "2002",
	},
	{
		id: 162,
		text: "Se podes olhar, vê. Se podes ver, repara.",
		author: "José Saramago",
		year: "1995",
	},
	{
		id: 163,
		text: "Para atravessar a noite é preciso acender as estrelas.",
		author: "Sophia de Mello Breyner",
		year: "1962",
	},
	{
		id: 164,
		text: "Não faças o que queres, faz o que deves para seres quem és.",
		author: "Agostinho da Silva",
		year: "1988",
	},
	{
		id: 165,
		text: "O tempo não cura nada, apenas nos ensina a conviver com as cicatrizes.",
		author: "António Lobo Antunes",
		year: "1990",
	},
	{
		id: 166,
		text: "Abra os braços para as mudanças, mas não abra mão dos seus valores.",
		author: "Dalai Lama",
		year: "1998",
	},
	{
		id: 167,
		text: "Não há caminho para a paz; a paz é o caminho.",
		author: "Thich Nhat Hanh",
		year: "1991",
	},
	{
		id: 168,
		text: "Onde quer que você esteja, esteja lá por inteiro.",
		author: "Eckhart Tolle",
		year: "1997",
	},
	{
		id: 169,
		text: "Em meio ao movimento e ao caos, mantenha a quietude dentro de você.",
		author: "Deepak Chopra",
		year: "1994",
	},
	{
		id: 170,
		text: "A mudança é difícil no começo, confusa no meio e linda no final.",
		author: "Robin Sharma",
		year: "2010",
	},
	{
		id: 171,
		text: "Líderes não criam seguidores, eles criam mais líderes.",
		author: "Simon Sinek",
		year: "2014",
	},
	{
		id: 172,
		text: "Comece com o objetivo final em mente.",
		author: "Stephen Covey",
		year: "1989",
	},
	{
		id: 173,
		text: "É nos momentos de decisão que o seu destino é traçado.",
		author: "Tony Robbins",
		year: "1991",
	},
	{
		id: 174,
		text: "Saia da sua zona de conforto. Você só pode crescer se estiver disposto a se sentir desconfortável.",
		author: "Brian Tracy",
		year: "2001",
	},
	{
		id: 175,
		text: "A paixão é o início do sucesso.",
		author: "Robert Kiyosaki",
		year: "1997",
	},
	{
		id: 176,
		text: "O que a mente do homem pode conceber e acreditar, ela pode alcançar.",
		author: "Napoleon Hill",
		year: "1937",
	},
	{
		id: 177,
		text: "Mude seus pensamentos e você mudará seu mundo.",
		author: "Norman Vincent Peale",
		year: "1952",
	},
	{
		id: 178,
		text: "A vida é 10% o que acontece comigo e 90% como eu reajo a isso.",
		author: "Charles R. Swindoll",
		year: "1982",
	},
	{
		id: 179,
		text: "Definitividade de propósito é o ponto de partida de todas as realizações.",
		author: "W. Clement Stone",
		year: "1962",
	},
	{
		id: 180,
		text: "Nós nos tornamos aquilo em que pensamos na maior parte do tempo.",
		author: "Earl Nightingale",
		year: "1956",
	},
	{
		id: 181,
		text: "Um líder é aquele que conhece o caminho, vai pelo caminho e mostra o caminho.",
		author: "John C. Maxwell",
		year: "1998",
	},
	{
		id: 182,
		text: "Não procure clientes para seus produtos, procure produtos para seus clientes.",
		author: "Seth Godin",
		year: "2008",
	},
	{
		id: 183,
		text: "Trabalho duro supera o talento quando o talento não trabalha duro.",
		author: "Gary Vaynerchuk",
		year: "2011",
	},
	{
		id: 184,
		text: "O oposto da felicidade não é a tristeza, é o tédio.",
		author: "Tim Ferriss",
		year: "2007",
	},
	{
		id: 185,
		text: "O planejamento de longo prazo não lida com decisões futuras, mas com o futuro das decisões presentes.",
		author: "Peter Drucker",
		year: "1974",
	},
	{
		id: 186,
		text: "Crie coisas das quais você se orgulhe.",
		author: "Clayton Christensen",
		year: "2012",
	},
	{
		id: 187,
		text: "A dor somada à reflexão resulta em progresso.",
		author: "Ray Dalio",
		year: "2017",
	},
	{
		id: 188,
		text: "A paz é a felicidade em repouso, e a felicidade é a paz em movimento.",
		author: "Naval Ravikant",
		year: "2020",
	},
	{
		id: 189,
		text: "Dificuldades reforçam a mente, assim como o trabalho reforça o corpo.",
		author: "Nassim Nicholas Taleb",
		year: "2012",
	},
	{
		id: 190,
		text: "Nada na vida é tão importante quanto você pensa que é enquanto está pensando nisso.",
		author: "Daniel Kahneman",
		year: "2011",
	},
	{
		id: 191,
		text: "A alma é tingida com a cor dos seus pensamentos.",
		author: "Marco Aurélio",
		year: "175",
	},
	{
		id: 192,
		text: "Primeiro diga a si mesmo o que você seria; e então faça o que tem que fazer.",
		author: "Epicteto",
		year: "100",
	},
	{
		id: 193,
		text: "A gratidão não é apenas a maior das virtudes, mas a mãe de todas as outras.",
		author: "Cícero",
		year: "55 a.C.",
	},
	{
		id: 194,
		text: "Enquanto adiamos, a vida passa.",
		author: "Sêneca",
		year: "49",
	},
	{
		id: 195,
		text: "A primeira e maior vitória é conquistar a si mesmo.",
		author: "Platão",
		year: "380 a.C.",
	},
	{
		id: 196,
		text: "O conhecimento de si mesmo é o começo de toda sabedoria.",
		author: "Aristóteles",
		year: "340 a.C.",
	},
	{
		id: 197,
		text: "Ninguém pode entrar no mesmo rio duas vezes.",
		author: "Heráclito",
		year: "500 a.C.",
	},
	{
		id: 198,
		text: "Conserve o seu direito de pensar, pois até pensar errado é melhor do que não pensar.",
		author: "Hipátia",
		year: "400",
	},
	{
		id: 199,
		text: "Não estrague o que você tem desejando o que não tem.",
		author: "Epicuro",
		year: "300 a.C.",
	},
	{
		id: 200,
		text: "É preciso ter fé para ver o invisível e alcançar o impossível.",
		author: "Tomás de Aquino",
		year: "1265",
	},
	{
		id: 201,
		text: "O amor é a beleza da alma.",
		author: "Santo Agostinho",
		year: "400",
	},
	{
		id: 202,
		text: "A prevenção é melhor que a cura.",
		author: "Erasmo de Roterdão",
		year: "1500",
	},
	{
		id: 203,
		text: "O maior conhecimento é saber como pertencer a si mesmo.",
		author: "Michel de Montaigne",
		year: "1580",
	},
	{
		id: 204,
		text: "O coração tem razões que a própria razão desconhece.",
		author: "Blaise Pascal",
		year: "1670",
	},
	{
		id: 205,
		text: "A paz não é a ausência de guerra, é uma virtude baseada na força de espírito.",
		author: "Baruch Spinoza",
		year: "1670",
	},
	{
		id: 206,
		text: "A leitura fornece conhecimento à mente; o pensamento transforma o que lemos em nosso.",
		author: "John Locke",
		year: "1690",
	},
	{
		id: 207,
		text: "Podemos melhorar o mundo tornando-nos melhores.",
		author: "Gottfried Wilhelm Leibniz",
		year: "1710",
	},
	{
		id: 208,
		text: "Para ser verdadeiramente grande, é preciso estar com as pessoas, não acima delas.",
		author: "Montesquieu",
		year: "1748",
	},
	{
		id: 209,
		text: "Dormi e sonhei que a vida era alegria. Acordei e vi que a vida era serviço.",
		author: "Immanuel Kant",
		year: "1790",
	},
];
